apiVersion: apps/v1
kind: Deployment
metadata:
name: cuaca
labels:
  app: cuaca
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: cuaca
      tier: cuaca
  spec:
    containers:
    - name: cuaca
      image: anggit/cuaca:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 5000
        name: cuaca

---
apiVersion: v1
kind: Service
metadata:
name: cuaca
labels:
  app: cuaca
spec:
ports:
  - port: 5000
    targetPort: 5000
selector:
  app: cuaca
  tier: cuaca
type: LoadBalancer
