apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuaca-app
spec:
  selector:
    matchLabels:
      app: cuaca
  replicas: 1
  template:
    metadata:
      labels:
        app: cuaca
    spec:
      containers:
      - name: cuaca
        image: "anggit/cuaca:latest"
        
---

apiVersion: v1
kind: Service
metadata:
  name: cuaca-service
  labels:
    app: cuaca
spec:
  type: LoadBalancer
  selector:
    app: cuaca
  ports:
  - port: 80
    protocol: http
